SELECT 1 ABCD,
       MAX(CASE WHEN SEQ = 1 THEN MONTH_NAME END)  AS MONTH_NAME1,
       MAX(CASE WHEN SEQ = 2 THEN MONTH_NAME END)  AS MONTH_NAME2,
       MAX(CASE WHEN SEQ = 3 THEN MONTH_NAME END)  AS MONTH_NAME3,
       MAX(CASE WHEN SEQ = 4 THEN MONTH_NAME END)  AS MONTH_NAME4,
       MAX(CASE WHEN SEQ = 5 THEN MONTH_NAME END)  AS MONTH_NAME5,
       MAX(CASE WHEN SEQ = 6 THEN MONTH_NAME END)  AS MONTH_NAME6,
       MAX(CASE WHEN SEQ = 7 THEN MONTH_NAME END)  AS MONTH_NAME7,
       MAX(CASE WHEN SEQ = 8 THEN MONTH_NAME END)  AS MONTH_NAME8,
       MAX(CASE WHEN SEQ = 9 THEN MONTH_NAME END)  AS MONTH_NAME9,
       MAX(CASE WHEN SEQ = 10 THEN MONTH_NAME END) AS MONTH_NAME10,
       MAX(CASE WHEN SEQ = 11 THEN MONTH_NAME END) AS MONTH_NAME11,
       MAX(CASE WHEN SEQ = 12 THEN MONTH_NAME END) AS MONTH_NAME12,
       MAX(CASE WHEN SEQ = 13 THEN MONTH_NAME END) AS MONTH_NAME13
FROM (
    SELECT 
        ROW_NUMBER() OVER (ORDER BY MCODE ASC) AS SEQ,
        MONTH_NAME
    FROM ADMMONTH
    WHERE DTFR BETWEEN (
              SELECT DTFR
              FROM ADMMONTH
              WHERE TO_DATE('@ASON@', 'YYYY-MM-DD') - INTERVAL '12 MONTH' 
                    BETWEEN DTFR AND DTTO
          )
          AND (
              SELECT DTFR
              FROM ADMMONTH
              WHERE TO_DATE('@ASON@', 'YYYY-MM-DD') 
                    BETWEEN DTFR AND DTTO
          )
    ORDER BY MCODE ASC
)