/* Formatted on 2025-02-26 16:18:50 (QP5 v5.294) */
/*
Purpose              Object                        ID              Developer          
Custom Development   CQ_JOB_ORDER                  394943          Dipankar
*/
with SITE_DATA
     as (
select
	ST.CODE SITECODE,
	ST.NAME NAME,
	ST.SHRTNAME SHORT_CODE,
	ST.ADDRESS ADDRESS,
	ST.CTNAME CITY,
	B.STNAME STATE,
	B.DIST DISTRICT,
	ST.PIN PINCODE,
	ST.OPH1 PHONE1,
	ST.OPH2 PHONE2,
	ST.OPH3 PHONE3,
	ST.EMAIL1 EMAIL1,
	ST.EMAIL2 EMAIL2,
	case
		when SITETYPE like '%OO-CM'
		or SITETYPE = 'MS-CO-CM'
                   then
                      SIN.GSTIN_NO
		else
                      ST.CP_GSTIN_NO
	end
                   GST_IDENTIFICATION_NO,
	case
		when SITETYPE like '%OO-CM'
		or SITETYPE = 'MS-CO-CM'
                   then
                      SIN.ADMGSTSTATE_CODE
		else
                      ST.CP_GSTIN_STATE_CODE
	end
                   GST_STATE_CODE,
	case
		when SITETYPE like '%OO-CM'
		or SITETYPE = 'MS-CO-CM'
                   then
                      STA.NAME
		else
                      STA1.NAME
	end
                   GST_STATE_NAME,
	case
		when ST.SITETYPE like '%OM%'
                   then
                      case
			when ISBILLINGSHIPPINGSAME = 'Y' then F.SLNAME
			else ST.SHIP_LEGAL_NAME
		end
		else
                      O.NAME
	end
                   SHIPPING_COMPANY_NAME,
	case
		when ISBILLINGSHIPPINGSAME = 'Y' then ST.ADDRESS
		else ST.SHIP_ADDRESS
	end
                   SHIPPING_ADDRESS,
	case
		when ISBILLINGSHIPPINGSAME = 'Y' then ST.CTNAME
		else ST.SHIP_CTNAME
	end
                   SHIPPING_CITY,
	case
		when ISBILLINGSHIPPINGSAME = 'Y' then ST.PIN
		else ST.SHIP_PIN
	end
                   SHIPPING_PINCODE,
	case
		when ISBILLINGSHIPPINGSAME = 'Y' then ST.OPH1
		else ST.SHIP_OPH1
	end
                   SHIPPING_PHONE1,
	case
		when ISBILLINGSHIPPINGSAME = 'Y' then ST.OPH2
		else ST.SHIP_OPH2
	end
                   SHIPPING_PHONE2,
	case
		when ISBILLINGSHIPPINGSAME = 'Y' then ST.OPH3
		else ST.SHIP_OPH3
	end
                   SHIPPING_PHONE3,
	case
		when ISBILLINGSHIPPINGSAME = 'Y' then ST.EMAIL1
		else ST.SHIP_EMAIL1
	end
                   SHIPPING_EMAIL1,
	case
		when ST.SITETYPE like '%CM'
                   then
                      SIN.GSTIN_NO
		else
                      case
			when ISBILLINGSHIPPINGSAME = 'Y' then ST.CP_GSTIN_NO
			else ST.SHIP_CP_GSTIN_NO
		end
	end
                   SHIPPING_GST_IDENTIFICATION_NO,
	case
		when ST.SITETYPE like '%CM'
                   then
                      SIN.ADMGSTSTATE_CODE
		else
                      case
			when ISBILLINGSHIPPINGSAME = 'Y'
                         then
                            ST.CP_GSTIN_STATE_CODE
			else
                            ST.SHIP_CP_GSTIN_STATE_CODE
		end
	end
                   SHIPPING_GST_STATE_CODE,
	case
		when ST.SITETYPE like '%CM'
                   then
                      STA.NAME
		else
                      case
			when ISBILLINGSHIPPINGSAME = 'Y' then STA1.NAME
			else STA2.NAME
		end
	end
                   SHIPPING_GST_STATE_NAME
from
	ADMSITE ST
left outer join FINSL F on
	ST.SLCODE = F.SLCODE
left outer join ADMCITY B on
	ST.CTNAME = B.CTNAME
left outer join ADMOU O on
	ST.ADMOU_CODE = O.CODE
left outer join ADMGSTIN SIN on
	ST.ADMGSTIN_CODE = SIN.CODE
left outer join ADMGSTSTATE STA
                   on
	SIN.ADMGSTSTATE_CODE = STA.CODE
left outer join ADMGSTSTATE STA1
                   on
	ST.CP_GSTIN_STATE_CODE = STA1.CODE
left outer join ADMGSTSTATE STA2
                   on
	ST.SHIP_CP_GSTIN_STATE_CODE = STA2.CODE)
select
	GINVIEW.FNC_UK() UK,
	H.CODE L1_JOBCODE,
	H.JOB_ORDER_NO L1_JOB_ORDER_NO,
	H.JOB_ORDER_DATE L1_JOB_ORDER_DATE,
	H.REFERENCE_NO L1_REFERENCE_NO,
	H.PCODE L1_PCODE,
	H.PRCODE L1_PRCODE,
	H.PROCESS_NAME L1_PROCESS_NAME,
	H.JOB_ORDER_TYPE L1_JOB_ORDER_TYPE,
	H.REMARKS L1_REMARKS,
	H.ADMOU_CODE L1_ADMOU_CODE,
	H.IS_CLOSED L1_IS_CLOSED,
	H.CREATED_ON L1_CREATED_ON,
	H.CREATED_BY L1_CREATED_BY,
	H.LAST_MODIFIED_ON L1_LAST_MODIFIED_ON,
	H.ADMSITE_CODE L1_ADMSITE_CODE,
	H.JOBBER_LOCCODE L1_JOBBER_LOCCODE,
	H.JOBBER_WIP_STOCKPOINT L1_JOBBER_WIP_STOCKPOINT,
	H.REFERENCE_DATE L1_REFERENCE_DATE,
	H.PRDJOBMAIN_UDFSTRING01 L1_PRDJOBMAIN_UDFSTRING01,
	H.PRDJOBMAIN_UDFSTRING02 L1_PRDJOBMAIN_UDFSTRING02,
	H.PRDJOBMAIN_UDFSTRING03 L1_PRDJOBMAIN_UDFSTRING03,
	H.PRDJOBMAIN_UDFSTRING04 L1_PRDJOBMAIN_UDFSTRING04,
	H.PRDJOBMAIN_UDFSTRING05 L1_PRDJOBMAIN_UDFSTRING05,
	H.PRDJOBMAIN_UDFSTRING06 L1_PRDJOBMAIN_UDFSTRING06,
	H.PRDJOBMAIN_UDFSTRING07 L1_PRDJOBMAIN_UDFSTRING07,
	H.PRDJOBMAIN_UDFSTRING08 L1_PRDJOBMAIN_UDFSTRING08,
	H.PRDJOBMAIN_UDFSTRING09 L1_PRDJOBMAIN_UDFSTRING09,
	H.PRDJOBMAIN_UDFSTRING10 L1_PRDJOBMAIN_UDFSTRING10,
	H.PRDJOBMAIN_UDFNUM01 L1_PRDJOBMAIN_UDFNUM01,
	H.PRDJOBMAIN_UDFNUM02 L1_PRDJOBMAIN_UDFNUM02,
	H.PRDJOBMAIN_UDFNUM03 L1_PRDJOBMAIN_UDFNUM03,
	H.PRDJOBMAIN_UDFNUM04 L1_PRDJOBMAIN_UDFNUM04,
	H.PRDJOBMAIN_UDFNUM05 L1_PRDJOBMAIN_UDFNUM05,
	H.PRDJOBMAIN_UDFDATE01 L1_PRDJOBMAIN_UDFDATE01,
	H.PRDJOBMAIN_UDFDATE02 L1_PRDJOBMAIN_UDFDATE02,
	H.PRDJOBMAIN_UDFDATE03 L1_PRDJOBMAIN_UDFDATE03,
	H.PRDJOBMAIN_UDFDATE04 L1_PRDJOBMAIN_UDFDATE04,
	H.PRDJOBMAIN_UDFDATE05 L1_PRDJOBMAIN_UDFDATE05,
	H.AUTHORIZED_BY L1_AUTHORIZED_BY,
	H.AUTHORIZED_ON L1_AUTHORIZED_ON,
	H.CUST_NAME L1_CUST_NAME,
	H.CUST_BILLING_ADDRESS L1_CUST_BILLING_ADDRESS,
	H.CUST_BILLING_CONTACT_PERSON L1_CUST_BILLING_CONTACT_PERSON,
	H.CUST_BILLING_CITY L1_CUST_BILLING_CITY,
	H.CUST_BILLING_STATE L1_CUST_BILLING_STATE,
	H.CUST_BILLING_DISTRICT L1_CUST_BILLING_DISTRICT,
	H.CUST_BILLING_ZONE L1_CUST_BILLING_ZONE,
	H.CUST_BILLING_EMAIL1 L1_CUST_BILLING_EMAIL1,
	H.CUST_BILLING_EMAIL2 L1_CUST_BILLING_EMAIL2,
	H.CUST_BILLING_FAX L1_CUST_BILLING_FAX,
	H.CUST_BILLING_MOBILE L1_CUST_BILLING_MOBILE,
	H.CUST_BILLING_OFFICE_PHONE1 L1_CUST_BILLING_OFFICE_PHONE1,
	H.CUST_BILLING_OFFICE_PHONE2 L1_CUST_BILLING_OFFICE_PHONE2,
	H.CUST_BILLING_OFFICE_PHONE3 L1_CUST_BILLING_OFFICE_PHONE3,
	H.CUST_BILLING_PINCODE L1_CUST_BILLING_PINCODE,
	H.CUST_BILLING_WEBSITE L1_CUST_BILLING_WEBSITE,
	H.CUST_GSTIN_NO L1_CUST_GSTIN_NO,
	H.CUST_GST_STATE_NAME L1_CUST_GST_STATE_NAME,
	H.CUST_GST_STATE_CODE L1_CUST_GST_STATE_CODE,
	H.CUST_DELIVERY_DUE_DAYS L1_CUST_DELI_DUE_DAYS,
	H.ORGUNIT_NAME L1_ORGUNIT_NAME,
	H.ORGUNIT_WEBSITE L1_ORGUNIT_WEBSITE,
	H.ORGUNIT_CIN L1_ORGUNIT_CIN,
	H.OWNER_SITE_NAME L1_OWNER_SITE_NAME,
	H.OWNER_SHORT_CODE L1_OWNER_SHORT_CODE,
	H.OWNER_SITE_ADDRESS L1_OWNER_SITE_ADDRESS,
	H.OWNER_SITE_CITY L1_OWNER_SITE_CITY,
	H.OWNER_SITE_PINCODE L1_OWNER_SITE_PINCODE,
	H.OWNER_SITE_PHONE1 L1_OWNER_SITE_PHONE1,
	H.OWNER_SITE_PHONE2 L1_OWNER_SITE_PHONE2,
	H.OWNER_SITE_PHONE3 L1_OWNER_SITE_PHONE3,
	H.OWNER_SITE_EMAIL1 L1_OWNER_SITE_EMAIL1,
	H.OWNER_SITE_EMAIL2 L1_OWNER_SITE_EMAIL2,
	H.OWNER_GST_IDENTIFICATION_NO L1_OWNER_GST_IDENTIFICATION_NO,
	H.OWNER_GST_STATE_CODE L1_OWNER_GST_STATE_CODE,
	H.OWNER_GST_STATE_NAME L1_OWNER_GST_STATE_NAME,
	LVL,
	SEQ,
	T.ASM_BARCODE L2_ASM_BARCODE,
	T.ASM_DIVISION L2_ASM_DIVISION,
	T.ASM_SECTION L2_ASM_SECTION,
	T.ASM_DEPARTMENT L2_ASM_DEPARTMENT,
	T.ASM_ITEM_ARTICLE_NAME L2_ASM_ITEM_ART_NAME,
	T.ASM_ITEM_CATEGORY1 L2_ASM_ITEM_CAT1,
	T.ASM_ITEM_CATEGORY2 L2_ASM_ITEM_CAT2,
	T.ASM_ITEM_CATEGORY3 L2_ASM_ITEM_CAT3,
	T.ASM_ITEM_CATEGORY6 L2_ASM_ITEM_CAT6,
	T.ASM_STRING_DESC2 L2_ASM_ITEM_DESC2,
	T.ASM_STRING_DESC5 L2_ASM_ITEM_DESC5,
	T.ASM_ITEM_UOM L2_ASM_ITEM_UOM,
	T.ASM_ITEM_HSN L2_ASM_ITEM_HSN,
	T.COM_BARCODE L3_COM_BARCODE,
	T.COM_DIVISION L3_COM_DIVISION,
	T.COM_SECTION L3_COM_SECTION,
	T.COM_DEPARTMENT L3_COM_DEPARTMENT,
	T.COM_ITEM_ARTICLE_NAME L3_COM_ITEM_ART_NAME,
	T.COM_ITEM_CATEGORY1 L3_COM_ITEM_CATE1,
	T.COM_ITEM_CATEGORY2 L3_COM_ITEM_CATE2,
	T.COM_ITEM_CATEGORY3 L3_COM_ITEM_CATE3,
	T.COM_ITEM_CATEGORY4 L3_COM_ITEM_CATE4,
	T.COM_ITEM_CATEGORY5 L3_COM_ITEM_CATE5,
	T.COM_ITEM_CATEGORY6 L3_COM_ITEM_CATE6,
	T.COM_ITEM_VENDOR L3_COM_ITEM_VENDOR,
	T.COM_ITEM_UOM L3_COM_ITEM_UOM,
	T.COM_ITEM_HSN L3_COM_ITEM_HSN,
	T.ASM_ITEM_TYPE L2_ASM_ITEM_TYPE,
	T.ASM_ICODE L2_ASM_ICODE,
	T.ASM_LOTCODE L2_ASM_LOTCODE,
	T.ASM_PLAN_NO L2_ASM_PLAN_NO,
	T.ASM_QUANTITY L2_ASM_QUANTITY,
	T.ASM_RATE L2_ASM_RATE,
	T.ASM_ITEM_REMARKS L2_ASM_ITEM_REMARKS,
	T.ASM_DUE_DATE L2_ASM_DUE_DATE,
	T.ASM_SAITEM_CODE L2_ASM_SAITEM_CODE,
	T.ASM_SUB_ASSEMBLY_ITEM L2_ASM_SUB_ASSEM_ITEM,
	T.COM_ITEM_TYPE L3_COM_ITEM_TYPE,
	T.COM_ICODE L3_COM_ICODE,
	T.COM_QUANTITY L3_COM_QUANTITY,
	T.COM_ITEM_REMARKS L3_COM_ITEM_REMARKS,
	T.COM_SAITEM_CODE L3_COM_SAITEM_CODE,
	T.com_plan_no L3_COM_PLAN_NO
from
	(
	select
		M.CODE UK,
		M.CODE CODE,
		M.JOBNO JOB_ORDER_NO,
		DOC.DOCNAME NUMBERING_SCHEME,
		M.JOB_DATE JOB_ORDER_DATE,
		M.REF_NO REFERENCE_NO,
		M.PCODE PCODE,
		M.PRCODE,
		P.PRNAME PROCESS_NAME,
		INITCAP (
                  case
			when M.JOBTYPE = 'LS' then 'WPLAN BASED STANDARD'
			when M.JOBTYPE = 'LN' then 'WPLAN BASED NONSTANDARD'
			when M.JOBTYPE = 'AS' then 'ADHOC'
			when M.JOBTYPE = 'AN' then 'ADHOC REPROCESS'
		end)
                  JOB_ORDER_TYPE,
		M.REMARKS,
		M.ADMOU_CODE,
		INITCAP (
                  case
			when M.IS_CLOSED = 'Y' then 'YES'
			when M.IS_CLOSED = 'N' then 'NO'
		end)
                  IS_CLOSED,
		M.TIME CREATED_ON,
		C.FNAME || ' ' || '[' || C.ENO || ']' CREATED_BY,
		M.LAST_ACCESS_TIME LAST_MODIFIED_ON,
		case
			when LAST_ACCESS_ECODE is not null
                  then
                     L1.FNAME || ' ' || '[' || L1.ENO || ']'
			else
                     null
		end
                  LAST_MODIFIED_BY,
		M.ADMSITE_CODE ADMSITE_CODE,
		M.JOBBER_LOCCODE JOBBER_LOCCODE,
		L.LOCNAME JOBBER_WIP_STOCKPOINT,
		M.REF_DT REFERENCE_DATE,
		M.YCODE,
		Y.YNAME,
		M.UDFSTRING01 PRDJOBMAIN_UDFSTRING01,
		M.UDFSTRING02 PRDJOBMAIN_UDFSTRING02,
		M.UDFSTRING03 PRDJOBMAIN_UDFSTRING03,
		M.UDFSTRING04 PRDJOBMAIN_UDFSTRING04,
		M.UDFSTRING05 PRDJOBMAIN_UDFSTRING05,
		M.UDFSTRING06 PRDJOBMAIN_UDFSTRING06,
		M.UDFSTRING07 PRDJOBMAIN_UDFSTRING07,
		M.UDFSTRING08 PRDJOBMAIN_UDFSTRING08,
		M.UDFSTRING09 PRDJOBMAIN_UDFSTRING09,
		M.UDFSTRING10 PRDJOBMAIN_UDFSTRING10,
		M.UDFNUM01 PRDJOBMAIN_UDFNUM01,
		M.UDFNUM02 PRDJOBMAIN_UDFNUM02,
		M.UDFNUM03 PRDJOBMAIN_UDFNUM03,
		M.UDFNUM04 PRDJOBMAIN_UDFNUM04,
		M.UDFNUM05 PRDJOBMAIN_UDFNUM05,
		M.UDFDATE01 PRDJOBMAIN_UDFDATE01,
		M.UDFDATE02 PRDJOBMAIN_UDFDATE02,
		M.UDFDATE03 PRDJOBMAIN_UDFDATE03,
		M.UDFDATE04 PRDJOBMAIN_UDFDATE04,
		M.UDFDATE05 PRDJOBMAIN_UDFDATE05,
		H.FNAME || '[' || C.ENO || ']' AUTHORIZED_BY,
		M.AUTH_TIME AUTHORIZED_ON,
		CUST_NAME,
		CUST_BILLING_ADDRESS,
		CUST_BILLING_CONTACT_PERSON,
		CUST_BILLING_CITY,
		CUST_BILLING_STATE,
		CUST_BILLING_DISTRICT,
		CUST_BILLING_ZONE,
		CUST_BILLING_EMAIL1,
		CUST_BILLING_EMAIL2,
		CUST_BILLING_FAX,
		CUST_BILLING_MOBILE,
		CUST_BILLING_OFFICE_PHONE1,
		CUST_BILLING_OFFICE_PHONE2,
		CUST_BILLING_OFFICE_PHONE3,
		CUST_BILLING_PINCODE,
		CUST_BILLING_WEBSITE,
		CUST_GSTIN_NO,
		CUST_GST_STATE_NAME,
		CUST_GST_STATE_CODE,
		CUST_DELIVERY_DUE_DAYS,
		OU.NAME ORGUNIT_NAME,
		OU.WEBSITE ORGUNIT_WEBSITE,
		OU.CINNO ORGUNIT_CIN,
		OS.NAME OWNER_SITE_NAME,
		OS.SHORT_CODE OWNER_SHORT_CODE,
		OS.ADDRESS OWNER_SITE_ADDRESS,
		OS.CITY OWNER_SITE_CITY,
		OS.PINCODE OWNER_SITE_PINCODE,
		OS.PHONE1 OWNER_SITE_PHONE1,
		OS.PHONE2 OWNER_SITE_PHONE2,
		OS.PHONE3 OWNER_SITE_PHONE3,
		OS.EMAIL1 OWNER_SITE_EMAIL1,
		OS.EMAIL2 OWNER_SITE_EMAIL2,
		OS.GST_IDENTIFICATION_NO
                  OWNER_GST_IDENTIFICATION_NO,
		OS.GST_STATE_CODE OWNER_GST_STATE_CODE,
		OS.GST_STATE_NAME OWNER_GST_STATE_NAME
	from
		PRDJOBMAIN M
	inner join HRDEMP C on
		M.ECODE = C.ECODE
	inner join ADMOU OU on
		(M.ADMOU_CODE = OU.CODE)
	left outer join HRDEMP L1 on
		M.LAST_ACCESS_ECODE = L1.ECODE
	left outer join HRDEMP H on
		M.AUTH_ECODE = H.ECODE
	inner join PRDPR P on
		M.PRCODE = P.PRCODE
	left outer join ADMDOCSCHEME DOC on
		M.DOCCODE = DOC.DOCCODE
	inner join SITE_DATA OS on
		(M.ADMSITE_CODE = OS.SITECODE)
	left outer join INVLOC L on
		M.JOBBER_LOCCODE = L.LOCCODE
	inner join ADMYEAR Y on
		M.YCODE = Y.YCODE
	left outer join
               (
		select
			S.SLNAME CUST_NAME,
			S.SLCODE,
			S.BADDR CUST_BILLING_ADDRESS,
			S.BCP CUST_BILLING_CONTACT_PERSON,
			S.BCTNAME CUST_BILLING_CITY,
			BCT.STNAME CUST_BILLING_STATE,
			BCT.DIST CUST_BILLING_DISTRICT,
			BCT.ZONE CUST_BILLING_ZONE,
			S.BEMAIL CUST_BILLING_EMAIL1,
			S.BEMAIL2 CUST_BILLING_EMAIL2,
			S.BFX1 CUST_BILLING_FAX,
			S.BFX2 CUST_BILLING_MOBILE,
			S.BPH1 CUST_BILLING_OFFICE_PHONE1,
			S.BPH2 CUST_BILLING_OFFICE_PHONE2,
			S.BPH3 CUST_BILLING_OFFICE_PHONE3,
			S.BPIN CUST_BILLING_PINCODE,
			S.BWEBSITE CUST_BILLING_WEBSITE,
			S.CP_GSTIN_NO CUST_GSTIN_NO,
			GTE.NAME CUST_GST_STATE_NAME,
			S.CP_GSTIN_STATE_CODE CUST_GST_STATE_CODE,
			S.PUR_DUEDAYS CUST_DELIVERY_DUE_DAYS
		from
			FINSL S
		left outer join ADMCITY BCT on
			S.BCTNAME = BCT.CTNAME
		left outer join ADMGSTSTATE GTE
                          on
			S.CP_GSTIN_STATE_CODE = GTE.CODE) CUS
                  on
		(M.PCODE = CUS.SLCODE)
	where
		( M.CODE in (
		select
			unnest(regexp_matches('@DocumentId@',
			'[^|~|]+',
			'g'))::bigint as col1)
			or coalesce (nullif ('@DocumentId@',
			''),
			'0')::text = 0::text)) H
inner join
       (
	select
		D.*
	from
		(
		select
			'L2#DETAIL' LVL,
			1 SEQ,
			JOBCODE,
			BARCODE ASM_BARCODE,
			DIVISION ASM_DIVISION,
			section ASM_SECTION,
			DEPARTMENT ASM_DEPARTMENT,
			ARTICLE_NAME ASM_ITEM_ARTICLE_NAME,
			CATEGORY1 ASM_ITEM_CATEGORY1,
			CATEGORY2 ASM_ITEM_CATEGORY2,
			CATEGORY3 ASM_ITEM_CATEGORY3,
			CATEGORY6 ASM_ITEM_CATEGORY6,
			I.STRING_DESC2 ASM_STRING_DESC2,
			I.STRING_DESC5 ASM_STRING_DESC5,
			UOM ASM_ITEM_UOM,
			I.HSN_CODE ASM_ITEM_HSN,
			null COM_BARCODE,
			null COM_DIVISION,
			null COM_SECTION,
			null COM_DEPARTMENT,
			null COM_ITEM_ARTICLE_NAME,
			null COM_ITEM_CATEGORY1,
			null COM_ITEM_CATEGORY2,
			null COM_ITEM_CATEGORY3,
			null COM_ITEM_CATEGORY4,
			null COM_ITEM_CATEGORY5,
			null COM_ITEM_CATEGORY6,
			null COM_ITEM_VENDOR,
			null COM_ITEM_UOM,
			null COM_ITEM_HSN,
			ASM_ITEM_TYPE,
			ASM_ICODE,
			ASM_LOTCODE,
			ASM_PLAN_NO,
			ASM_QUANTITY,
			ASM_RATE,
			ASM_ITEM_REMARKS,
			ASM_DUE_DATE,
			ASM_SAITEM_CODE,
			ASM_SUB_ASSEMBLY_ITEM,
			COM_ITEM_TYPE,
			COM_ICODE,
			COM_QUANTITY,
			COM_ITEM_REMARKS,
			COM_SAITEM_CODE,
			com_plan_no
		from
			(
			select
				D.JOBCODE JOBCODE,
				'Assembly' ASM_ITEM_TYPE,
				D.ASSEMBLY_ICODE ASM_ICODE,
				D.LOTCODE ASM_LOTCODE,
				L.LOTNO ASM_PLAN_NO,
				SUM (D.QTY) ASM_QUANTITY,
				D.JOB_RATE ASM_RATE,
				D.REMARKS ASM_ITEM_REMARKS,
				D.DUEDT ASM_DUE_DATE,
				D.ASS_SAITEM_CODE ASM_SAITEM_CODE,
				S.SAINAME ASM_SUB_ASSEMBLY_ITEM,
				null COM_ITEM_TYPE,
				null COM_ICODE,
				0 COM_QUANTITY,
				0 BOM_QTY,
				null COM_ITEM_REMARKS,
				null COM_SAITEM_CODE,
				null com_plan_no
			from
				PRDJOBDET D
			left outer join PRDLOTMAIN L
                                    on
				D.LOTCODE = L.CODE
			left outer join PRD_SAITEM S
                                    on
				D.ASS_SAITEM_CODE = S.CODE
			group by
				D.JOBCODE,
				D.ASSEMBLY_ICODE,
				D.LOTCODE,
				L.LOTNO,
				D.JOB_RATE,
				D.REMARKS,
				D.DUEDT,
				D.ASS_SAITEM_CODE,
				S.SAINAME) D
		inner join GINVIEW.LV_ASSEMBLY_ITEM I
                          on
			(D.ASM_ICODE = I.CODE)
		where
			( JOBCODE in (
			select
				unnest(regexp_matches('@DocumentId@',
				'[^|~|]+',
				'g'))::bigint as col1)
				or coalesce (nullif ('@DocumentId@',
				''),
				'0')::text = 0::text)
	union all
		select
			'L3#DETAIL' LVL,
			3 SEQ,
			JOBCODE,
			null ASM_BARCODE,
			null ASM_DIVISION,
			null ASM_SECTION,
			null ASM_DEPARTMENT,
			null ASM_ITEM_ARTICLE_NAME,
			null ASM_ITEM_CATEGORY1,
			null ASM_ITEM_CATEGORY2,
			null ASM_ITEM_CATEGORY3,
			null ASM_ITEM_CATEGORY6,
			null ASM_STRING_DESC2,
			null ASM_STRING_DESC5,
			null ASM_ITEM_UOM,
			null ASM_ITEM_HSN,
			BARCODE COM_BARCODE,
			DIVISION COM_DIVISION,
			section COM_SECTION,
			DEPARTMENT COM_DEPARTMENT,
			ARTICLE_NAME COM_ITEM_ARTICLE_NAME,
			CATEGORY1 COM_ITEM_CATEGORY1,
			CATEGORY2 COM_ITEM_CATEGORY2,
			CATEGORY3 COM_ITEM_CATEGORY3,
			CATEGORY4 COM_ITEM_CATEGORY4,
			CATEGORY5 COM_ITEM_CATEGORY5,
			CATEGORY6 COM_ITEM_CATEGORY6,
			I.VENDOR COM_ITEM_VENDOR,
			UOM COM_ITEM_UOM,
			I.HSN_CODE COM_ITEM_HSN,
			ASM_ITEM_TYPE,
			ASM_ICODE,
			ASM_LOTCODE,
			ASM_PLAN_NO,
			ASM_QUANTITY,
			ASM_RATE,
			ASM_ITEM_REMARKS,
			ASM_DUE_DATE,
			ASM_SAITEM_CODE,
			ASM_SUB_ASSEMBLY_ITEM,
			COM_ITEM_TYPE,
			COM_ICODE,
			COM_QUANTITY,
			COM_ITEM_REMARKS,
			COM_SAITEM_CODE,
			com_plan_no
		from
			(
			select
				D.JOBCODE JOBCODE,
				null ASM_ITEM_TYPE,
				null ASM_ICODE,
				null::int ASM_LOTCODE,
				null ASM_PLAN_NO,
				0 ASM_QUANTITY,
				null::int ASM_RATE,
				null ASM_ITEM_REMARKS,
				null::date ASM_DUE_DATE,
				null::int ASM_SAITEM_CODE,
				null ASM_SUB_ASSEMBLY_ITEM,
				'Component' COM_ITEM_TYPE,
				D.COMPONENT_ICODE COM_ICODE,
				SUM (D.QTY) COM_QUANTITY,
				D.REMARKS COM_ITEM_REMARKS,
				D.COM_SAITEM_CODE::text COM_SAITEM_CODE,
				lot.lotno com_plan_no
			from
				PRDJOBBOM D
				left outer join prdlotmain lot on d.lotcode  = lot.code 
			left outer join PRD_SAITEM S
                                    on
				D.COM_SAITEM_CODE = S.CODE
			where
				D.ASSEMBLY_ICODE <> D.COMPONENT_ICODE
			group by
				D.JOBCODE,
				D.COMPONENT_ICODE,
				D.REMARKS,
				D.COM_SAITEM_CODE,
				lot.lotno) D
		inner join GINVIEW.LV_COMPONENT_ITEM I
                          on
			(D.COM_ICODE = I.CODE)
		where
			( JOBCODE in (
			select
				unnest(regexp_matches('@DocumentId@',
				'[^|~|]+',
				'g'))::bigint as col1)
				or coalesce (nullif ('@DocumentId@',
				''),
				'0')::text = 0::text)) D) T
          on
	(T.JOBCODE = H.CODE)