/*|| Custom Development || Object : CQ_BUFFER_STOCK || Ticket Id :  418095 || Developer : Dipankar ||*/
SELECT ROW_NUMBER() OVER() UK,
       I.CODE ICODE,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '2/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_2,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '3/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_3,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '4/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_4,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '5/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_5,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '6/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_6,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '7/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_7,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '8/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_8,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '9/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_9,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '10/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_10,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '11/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_11,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '12/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_12,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '13/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_13,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '14/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_14,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '15/' THEN  COALESCE (I.NUMERIC_DESC2, 0) ELSE 0 END) ITEM_NUMBER2_15,
       SUM (COALESCE(I.NUMERIC_DESC2,0))   TOTAL_ITEM_NUMBER2,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '2/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_2,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '3/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_3,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '4/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_4,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '5/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_5,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '6/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_6,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '7/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_7,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '8/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_8,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '9/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_9,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '10/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_10,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '11/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_11,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '12/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_12,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '13/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_13,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '14/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_14,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '15/' THEN  COALESCE (A.SO_QTY, 0) ELSE 0 END) SO_QTY_15,
       SUM (COALESCE (A.SO_QTY, 0))        TOTAL_SO_QTY,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '2/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_2,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '3/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_3,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '4/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_4,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '5/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_5,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '6/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_6,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '7/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_7,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '8/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_8,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '9/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_9,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '10/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_10,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '11/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_11,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '12/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_12,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '13/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_13,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '14/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_14,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '15/' THEN  COALESCE (B.PO_QTY,0) ELSE 0 END) PO_QTY_15,
       SUM (COALESCE (B.PO_QTY,0))         TOTAL_PO_QTY,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '2/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_2,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '3/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_3,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '4/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_4,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '5/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_5,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '6/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_6,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '7/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_7,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '8/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_8,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),2) = '9/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_9,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '10/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_10,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '11/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_11,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '12/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_12,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '13/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_13,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '14/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_14,
       SUM (CASE WHEN LEFT(TRIM(I.CATEGORY3),3) = '15/' THEN  COALESCE (C.SOH_QTY,0) ELSE 0 END) SOH_QTY_15,
       SUM (COALESCE (C.SOH_QTY,0))        TOTAL_SOH_QTY
  FROM MAIN.INVITEM_DETAIL_AGG I
       LEFT JOIN
       (SELECT D.ICODE, SUM (COALESCE (D.ORDQTY, 0) - COALESCE (D.cnlqty, 0) - COALESCE (D.dqty, 0)) SO_QTY
          FROM SALORDMAIN M
               INNER JOIN SALORDDET D ON M.ORDCODE = D.ORDCODE
               INNER JOIN MAIN.INVITEM_DETAIL_AGG I ON D.ICODE = I.CODE
         WHERE I.DEPARTMENT = 'FOOTWEAR' AND M.ORDDT::DATE <= CURRENT_DATE
         GROUP BY D.ICODE) A
          ON I.CODE = A.ICODE
       LEFT JOIN
       (SELECT D.ICODE, SUM (COALESCE (D.ORDQTY, 0) - COALESCE (D.cnlqty, 0) - COALESCE (D.rcqty, 0)) PO_QTY
          FROM PURORDMAIN M
               INNER JOIN PURORDDET D ON M.ORDCODE = D.ORDCODE
               INNER JOIN MAIN.INVITEM_DETAIL_AGG I ON D.ICODE = I.CODE
         WHERE M.ADMSITE_CODE = 1 and  I.DEPARTMENT = 'FOOTWEAR' AND M.ORDDT::DATE <= CURRENT_DATE
         GROUP BY D.ICODE) B
          ON I.CODE = B.ICODE
       LEFT JOIN
       (SELECT K.ICODE, SUM (COALESCE (K.QTY, 0)) SOH_QTY
          FROM INVSTOCK K
               LEFT JOIN INVLOC L ON K.LOCCODE = L.LOCCODE
               INNER JOIN MAIN.INVITEM_DETAIL_AGG I ON K.ICODE = I.CODE
         WHERE     L.LOCTYPE = 'B'
               AND I.DEPARTMENT = 'FOOTWEAR'
               AND K.ENTDT::DATE <= CURRENT_DATE
         GROUP BY K.ICODE) C
          ON I.CODE = C.ICODE
 WHERE I.DEPARTMENT = 'FOOTWEAR'
 GROUP BY I.CODE
 HAVING (SUM (COALESCE(I.NUMERIC_DESC2,0))<>0
    OR  SUM (COALESCE (A.SO_QTY, 0))<>0
    OR  SUM (COALESCE (B.PO_QTY, 0))<>0
    OR  SUM (COALESCE (C.SOH_QTY,0))<>0)