SELECT ORD.ORDCODE,
       LISTAGG(TO_CHAR(ORD.GRCDT, 'DD-MM-YYYY'), ', ')
         WITHIN GROUP (ORDER BY ORD.GRCDT ASC) AS GRC_DATE
  FROM (
        SELECT DISTINCT D.ORDCODE, M.GRCDT
          FROM INVGRCMAIN M
               INNER JOIN INVGRCDET D ON M.GRCCODE = D.GRCCODE
         WHERE D.ORDCODE IS NOT NULL
       ) ORD
GROUP BY ORD.ORDCODE