/*Against Ticket : 414849*/

SELECT GINVIEW.FNC_UK () UK,
         GENERAL_LEDGER_CODE GLCODE,
         SUB_LEDGER_CODE   SLCODE,
         MIN (DOCUMENT_DATE) MIN_DUE_DATE
    FROM V_ADJ
   WHERE PENDING <> 0
GROUP BY GENERAL_LEDGER_CODE, SUB_LEDGER_CODE
ORDER BY GENERAL_LEDGER_CODE, SUB_LEDGER_CODE