/*|| Custom Development || Object : CQ_PRODUCTION || Ticket Id :  418880,430662 || Developer : Dipankar ||*/
WITH MAIN AS (
SELECT
	SOM.ORDCODE,
	MPLAN.CODE MPLAN_CODE,
	SOM.SCHEME_DOCNO ORDER_NO,
	SOM.ORDDT::DATE ORDER_DATE,
	SOM.DUEDT::DATE ORDER_DUE_DATE,
	SOM.PCODE,
	CUS.SLNAME ORDER_CUSTOMER_NAME,
	MPLAN.PLANNO MPLAN_NO,
	MPLAN.SCHEDULE_DATE::DATE MPLAN_DATE,
	LOM.CODE LOTCODE,
	LOM.LOTNO WPLAN_NO,
	LOM.SCHEDULE_DATE::DATE WPLAN_DATE,
	LOD.ASSEMBLY_ICODE,
	SUM (SOD.ORDQTY) SO_QTY,
	SUM (MPDET.QTY) MPLAN_QTY,
	SUM (LOD.QTY) WPLAN_QTY
FROM
	PRDMPLANMAIN MPLAN
INNER JOIN PRDMPLANDET MPDET ON
	MPLAN.CODE = MPDET.PLANCODE
LEFT JOIN PRDMPLANALLOC MPALLOC
            ON
	MPDET.CODE = MPALLOC.PRDMPLANDET_CODE
LEFT JOIN PRDLOTDET LOD ON
	MPALLOC.CODE = LOD.PRDMPLANALLOC_CODE
LEFT JOIN PRDLOTMAIN LOM ON
	LOD.LOTCODE = LOM.CODE
LEFT JOIN SALORDMAIN SOM ON
	MPLAN.ORDCODE = SOM.ORDCODE
LEFT JOIN SALORDDET SOD ON
	SOD.ORDCODE = SOM.ORDCODE
LEFT JOIN FINSL CUS ON
	SOM.PCODE = CUS.SLCODE
WHERE
	MPLAN.SCHEDULE_DATE::DATE BETWEEN TO_DATE('@DTFR@', 'YYYY-MM-DD') AND TO_DATE('@DTTO@', 'YYYY-MM-DD')
GROUP BY
	SOM.ORDCODE,
	MPLAN.CODE,
	SOM.SCHEME_DOCNO,
	SOM.ORDDT::DATE,
	SOM.DUEDT::DATE,
	SOM.PCODE,
	CUS.SLNAME,
	MPLAN.PLANNO,
	MPLAN.SCHEDULE_DATE::DATE,
	LOM.CODE,
	LOM.LOTNO,
	LOM.SCHEDULE_DATE::DATE,
	LOD.ASSEMBLY_ICODE
UNION ALL
SELECT
	SOM.ORDCODE,
	NULL MPLAN_CODE,
	SOM.SCHEME_DOCNO ORDER_NO,
	SOM.ORDDT::DATE ORDER_DATE,
	SOM.DUEDT::DATE ORDER_DUE_DATE,
	SOM.PCODE,
	CUS.SLNAME ORDER_CUSTOMER_NAME,
	NULL MPLAN_NO,
	NULL MPLAN_DATE,
	LOM.CODE LOTCODE,
	LOM.LOTNO WPLAN_NO,
	LOM.SCHEDULE_DATE::DATE WPLAN_DATE,
	LOD.ASSEMBLY_ICODE,
	SUM (SOD.ORDQTY) SO_QTY,
	0 MPLAN_QTY,
	SUM (LOD.QTY) WPLAN_QTY
FROM
	PRDLOTDET LOD
INNER JOIN PRDLOTMAIN LOM ON
	LOD.LOTCODE = LOM.CODE
LEFT JOIN PRDLOT_SALORD LORD
            ON
	LOD.LOTCODE = LORD.PRDLOTMAIN_CODE
	AND LOD.ASSEMBLY_ICODE = LORD.ICODE
LEFT JOIN SALORDDET SOD
            ON
	LORD.SALORDMAIN_CODE = SOD.ORDCODE
	AND LORD.ICODE = SOD.ICODE
LEFT JOIN SALORDMAIN SOM ON
	SOD.ORDCODE = SOM.ORDCODE
LEFT JOIN FINSL CUS ON
	SOM.PCODE = CUS.SLCODE
WHERE
	LOD.PRDMPLANALLOC_CODE IS NULL
	AND LOM.SCHEDULE_DATE::DATE BETWEEN TO_DATE('@DTFR@', 'YYYY-MM-DD') AND TO_DATE('@DTTO@', 'YYYY-MM-DD')
GROUP BY
	SOM.ORDCODE,
	SOM.SCHEME_DOCNO,
	SOM.ORDDT::DATE,
	SOM.DUEDT::DATE,
	SOM.PCODE,
	CUS.SLNAME,
	LOM.CODE,
	LOM.LOTNO,
	LOM.SCHEDULE_DATE::DATE,
	LOD.ASSEMBLY_ICODE)
 SELECT
	ROW_NUMBER() OVER() UK,
	MAIN.ORDCODE,
	MAIN.MPLAN_CODE,
	MAIN.ORDER_NO,
	MAIN.ORDER_DATE,
	MAIN.ORDER_DUE_DATE,
	MAIN.PCODE,
	MAIN.ORDER_CUSTOMER_NAME,
	MAIN.MPLAN_NO,
	MAIN.MPLAN_DATE,
	MAIN.LOTCODE,
	MAIN.WPLAN_NO,
	MAIN.WPLAN_DATE,
	MAIN.ASSEMBLY_ICODE,
	MAIN.SO_QTY,
	MAIN.MPLAN_QTY,
	MAIN.WPLAN_QTY,
	DET.JOBCODE,
	DET.JOB_ORDER_NO,
	DET.JOB_ORDER_DATE,
	DET.JOBBER_NAME,
	DET.PROCESS_NAME,
	DET.REMARKS,
	DET.PRDJOBMAIN_UDFDATE01,
	DET.PRDJOBMAIN_UDFDATE02,
	DET.OPERATION_SEQUENCE,
	DET.ORDER_QUANTITY,
	DET.JOB_RATE,
	DET.PENDING_QUANTITY,
	DET.ORIGINAL_ORDER_QUANTITY,
	DET.COMPLETED_QUANTITY,
	DET.CANCEL_QUANTITY,
	DET.COMPONENT_ICODE,
	DET.COMPONENT_SUPPLY_TYPE,
	DET.TOTAL_COMPONENT_QUANTITY,
	DET.ISSUE_QUANTITY,
	DET.SHRINKAGE_PERCENT,
	DET.WIP_ISSUE_QTY,
	DET.TRANSACTION_NO,
	DET.TRANSACTION_DATE,
	DET.RECEIVED_QUANTITY,
	DET.JOB_RECEIPT_NO,
	DET.JOB_RECEIPT_DATE
FROM
	MAIN
LEFT JOIN (
	SELECT
		M.CODE JOBCODE,
		M.JOBNO JOB_ORDER_NO,
		M.JOB_DATE::DATE JOB_ORDER_DATE,
		S.SLNAME JOBBER_NAME,
		P.PRNAME PROCESS_NAME,
		M.REMARKS,
		M.UDFDATE01::DATE PRDJOBMAIN_UDFDATE01,
		M.UDFDATE02::DATE PRDJOBMAIN_UDFDATE02,
		JD.ASSEMBLY_ICODE,
		JD.LOTCODE,
		JD.OPERATION_SEQUENCE,
		JD.ORDER_QUANTITY,
		JD.JOB_RATE,
		JD.PENDING_QUANTITY,
		JD.ORIGINAL_ORDER_QUANTITY,
		JD.COMPLETED_QUANTITY,
		JD.CANCEL_QUANTITY,
		JDC.COMPONENT_ICODE,
		JDC.COMPONENT_SUPPLY_TYPE,
		JDC.TOTAL_COMPONENT_QUANTITY,
		JDC.ISSUE_QUANTITY,
		JDC.SHRINKAGE_PERCENT,
		WID.WIP_ISSUE_QTY,
		WIM.TRANSACTION_NO,
		WIM.TRANSACTION_DATE,
		JRD.RECEIVED_QUANTITY,
		JRM.JOB_RECEIPT_NO,
		JRM.JOB_RECEIPT_DATE
	FROM
		PRDJOBMAIN M
	INNER JOIN FINSL S ON
		M.PCODE = S.SLCODE
	INNER JOIN PRDPR P ON
		M.PRCODE = P.PRCODE
	INNER JOIN (
		SELECT
			D.JOBCODE JOBCODE,
			D.CODE,
			D.ASSEMBLY_ICODE ASSEMBLY_ICODE,
			D.LOTCODE,
			D.OPERATION_SEQ OPERATION_SEQUENCE,
			SUM (COALESCE(D.QTY, 0)) ORDER_QUANTITY,
			COALESCE(D.JOB_RATE, 0) JOB_RATE,
			SUM (COALESCE(D.P_QTY, 0)) PENDING_QUANTITY,
			SUM (COALESCE(D.O_QTY, 0)) ORIGINAL_ORDER_QUANTITY,
			SUM (COALESCE(D.COMPLETED_QTY, 0)) COMPLETED_QUANTITY,
			SUM (COALESCE(D.CNL_QTY, 0)) CANCEL_QUANTITY
		FROM
			PRDJOBDET D
		GROUP BY
			D.JOBCODE,
			D.CODE,
			D.ASSEMBLY_ICODE,
			D.LOTCODE,
			D.OPERATION_SEQ,
			D.JOB_RATE) JD ON
		M.CODE = JD.JOBCODE
	LEFT JOIN(
SELECT M.JOBCODE JOBCODE,
       M.PRDJOBDET_CODE PRDJOBDET_CODE,
       M.ASSEMBLY_ICODE ASSEMBLY_ICODE,
       LT.LOTNO PLAN_NO,
       M.COMPONENT_ICODE COMPONENT_ICODE,
       INITCAP (
          CASE
             WHEN M.SUPPLY_TYPE = 'P' THEN 'PUSH'
             WHEN M.SUPPLY_TYPE = 'O' THEN 'PULL-ON-ORDER'
             WHEN M.SUPPLY_TYPE = 'C' THEN 'PULL-ON-COMPLETION'
          END)
          COMPONENT_SUPPLY_TYPE,
       COALESCE(M.QTY, 0) TOTAL_COMPONENT_QUANTITY,
       COALESCE(M.ISSUED_QTY, 0) ISSUE_QUANTITY,
       COALESCE(M.RETURN_QTY, 0) RETURN_QUANTITY,
       COALESCE(M.WASTAGE_QTY, 0) WATSAGE_QUANTITY,
       COALESCE(M.CANCEL_QTY, 0) CANCEL_QUANTITY,
       COALESCE(M.ASSEMBLY_QTY, 0) ASSEMBLY_ITEM_QUNATITY,
       M.SHRINKAGE SHRINKAGE_PERCENT,
       COALESCE(M.CONSUMED_QTY, 0) CONSUMED_QUANTITY,
       COALESCE(M.SHORT_EXCESS_QTY, 0) SHORT_EXCESS_QTY,
       COALESCE(M.ALTERNATE_CNL_QTY, 0) ALTERANATE_CANCEL_QTY
  FROM PRDJOBBOM M LEFT OUTER JOIN PRDLOTMAIN LT ON M.LOTCODE = LT.CODE) JDC ON
		JD.CODE = JDC.PRDJOBDET_CODE
		AND JD.JOBCODE = JDC.JOBCODE
	LEFT JOIN (
		SELECT
			D.WIPTXN_CODE WIPTXN_CODE,
			D.JOBCODE JOBCODE,
			D.COMPONENT_ICODE COMPONENT_ICODE,
			D.ASSEMBLY_ICODE ASSEMBLY_ICODE,
			SUM (COALESCE(D.QTY, 0)) WIP_ISSUE_QTY
		FROM
			PRDWIPDET D
		GROUP BY
			D.WIPTXN_CODE,
			D.JOBCODE,
			D.COMPONENT_ICODE,
			D.ASSEMBLY_ICODE) WID ON
		JD.JOBCODE = WID.JOBCODE
		AND JD.ASSEMBLY_ICODE = WID.ASSEMBLY_ICODE
	LEFT JOIN (
		SELECT
			M.CODE CODE,
			M.WIPTXNNO TRANSACTION_NO,
			M.WIP_DATE::DATE TRANSACTION_DATE
		FROM
			PRDWIPMAIN M)WIM ON
		WID.WIPTXN_CODE = WIM.CODE
	LEFT JOIN (
		SELECT
			D.JRCCODE JRCCODE,
			D.JOBCODE JOBCODE,
			D.LOTCODE WPLANCODE,
			D.ASSEMBLY_ICODE,
			SUM (COALESCE(D.QTY, 0)) RECEIVED_QUANTITY
		FROM
			PRDJRCDET D
		GROUP BY
			D.JRCCODE,
			D.JOBCODE,
			D.LOTCODE,
			D.ASSEMBLY_ICODE) JRD ON
		JD.JOBCODE = JRD.JOBCODE
		AND JD.ASSEMBLY_ICODE = JRD.ASSEMBLY_ICODE
	LEFT JOIN(
SELECT M.CODE CODE, M.JRCNO JOB_RECEIPT_NO, M.JRC_DATE::DATE JOB_RECEIPT_DATE
  FROM PRDJRCMAIN M)JRM ON
		JRD.JRCCODE = JRM.CODE) DET ON
	MAIN.LOTCODE = DET.LOTCODE
	AND MAIN.ASSEMBLY_ICODE = DET.ASSEMBLY_ICODE